# —————————
# 基础设置
mixed-port: 7890
redir-port: 7891
tproxy-port: 1536
ipv6: true
mode: Rule
allow-lan: true
disable-keep-alive: true
geodata-mode: false
geo-auto-update: true
geo-update-interval: 24
updatetime: &Time 86400
geox-url:
  asn: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"
experimental:
  http-headers:
    request:
      - name: "User-Agent"
        value: "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Mobile Safari/537.36"
      - name: "Accept-Language"
        value: "en-US,en;q=0.9"
unified-delay: true
tcp-concurrent: true
log-level: silent # debug / silent
find-process-mode: always
#global-client-fingerprint: chrome 未来官方可能将移除，意义不大
external-controller: 0.0.0.0:9090 #修改端口后，如使用磁贴请重新正确设置API端口
external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip"
external-ui: "./webroot/Zash/"
secret: "" # 面板访问密码，如在公网访问建议设置
# —————————
# ==== Tips
# 1. 修改配置文件保存时，建议重启服务/重载配置.
# 2. 如使用 SurfingTile 的配置覆写，当前配置文件的某些字段应保持原有的完整性结构
# —————————
# 健康检查
p: &p
  type: http
  interval: *Time
  health-check:
    enable: true
    url: https://www.gstatic.com/generate_204
    interval: 300
  proxy: 订阅更新
  header: # 如遇订阅加载不出来请切换ua
      User-Agent:  # 使用注释法由上到下 默认使用第一个
        - "ClashMetaForAndroid/2.11.2.Meta"
        - "clash-verge/v2.2.3"
        - "ClashforWindows/0.19.23"
        - "clash.meta"
        - "mihomo"
# —————————
# 订阅地址相关
A: &A
  filter: "^(?!.*(套餐|重置|剩余|到期|订阅|群|账户|流量|有效期|时间|官网|失联|余额)).*$"
  use:
  - 1.主要地址
  - 2.备用地址
  - 3.额外地址
All: &All
  type: url-test
  use:
  - 1.主要地址
  - 2.备用地址
  - 3.额外地址
proxy-providers: # ← 此函数位置请勿变动！此为模块更新时备份恢复订阅变量范围 ↓
  1.主要地址: # 如遇订阅加载不出来，请尝试切换ua
    <<: *p
    override:
      additional-prefix: "Main："
    path: ./proxies/1.主要地址.yaml
    url: "此处引入您的Clash订阅链接地址"
  2.备用地址:
    <<: *p
    override:
      additional-prefix: "Minor："
    path: ./proxies/2.备用地址.yaml
    url: "此处引入您的Clash订阅链接地址"
  3.额外地址:
    <<: *p
    override:
      additional-prefix: "Additi："
    path: ./proxies/3.额外地址.yaml
    url: "此处引入您的Clash订阅链接地址"
# —————————
# 节点记忆
profile: # ← 此函数位置请勿变动！此为模块更新时备份恢复订阅变量范围 ↑
  store-selected: true
  store-fake-ip: true
# —————————
# 嗅探模块
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 5228, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain: # 如遇需内部通信的应用请放行该域名
    - "Mijia Cloud"
# —————————
# 网卡模块
# 如需使用 建议先阅读文档：https://wiki.metacubex.one/config/inbound/tun/
tun:
  enable: false
  device: Meta
  stack: gvisor
  dns-hijack:
    - any:53
    - tcp://any:53
  udp-timeout: 300
  auto-route: true
  strict-route: true
  auto-redirect: false
  auto-detect-interface: true
  # 如使用黑白名单这里需排除
  # exclude-package 排除 / include-package 包含
  exclude-package:
#    - com.samsung.android.messaging # 三星专供 ↓ 范围
#    - com.samsung.android.app.telephonyui
#    - com.samsung.android.dialer
#    - com.samsung.android.incallui
#    - com.samsung.android.smartcallprovider
#    - com.samsung.android.intellivoiceservice
#    - com.android.settings
#    - com.qti.qcc
#    - com.sec.epdg
#    - com.sec.imsservice # 三星专供 ↑ 范围
    # 非三星用户不必理会，三星用户需自行取消注释 不可使用include-package
# —————————
# DNS模块
# 请勿随意变动！
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip # redir-host
  fake-ip-range: 198.18.0.0/16
  fake-ip-range6: fdfe:dcba:9876::/48
  fake-ip-filter:
    - "RULE-SET:CN_域"
    - "RULE-SET:Private_域"
    - "RULE-SET:GoogleFCM_域"
    - "RULE-SET:自定义规则"
  proxy-server-nameserver:
    - https://1.12.12.12:443/dns-query#🌐 本机·本地直连&h3=false
    - https://120.53.53.53:443/dns-query#🌐 本机·本地直连&h3=false
    - https://223.5.5.5:443/dns-query#🌐 本机·本地直连&h3=true
    - https://223.6.6.6:443/dns-query#🌐 本机·本地直连&h3=true
  nameserver-policy:
    "RULE-SET:CN_域,Microsoft_域,Apple_域":
      - https://1.12.12.12:443/dns-query#🌐 本机·本地直连&h3=false
      - https://120.53.53.53:443/dns-query#🌐 本机·本地直连&h3=false
      - https://223.5.5.5:443/dns-query#🌐 本机·本地直连&h3=true
      - https://223.6.6.6:443/dns-query#🌐 本机·本地直连&h3=true
  nameserver:
    # Google
    - https://8.8.8.8:443/dns-query#DNS连接&h3=true
    - https://8.8.4.4:443/dns-query#DNS连接&h3=true
    # Cloudflare
    - https://1.1.1.1:443/dns-query#DNS连接&h3=true
    - https://1.0.0.1:443/dns-query#DNS连接&h3=true
  direct-nameserver:
    # 腾讯/阿里兜底
    # 正确配置本地后可移除 否则会卡[可选]
    - 1.12.12.12
    - 223.6.6.6
    # ----------------
    # 你的本地
    # 各大路由器/光猫默认 DNS
    - 192.168.1.1    # 请确保当前局域网可通
    # SIM卡运营商 [下方替换成你的运营商 一般有鉴权]
    - 120.80.80.80  # ← 替换成你想用的 或者删除
    - 221.5.88.88   # ← 替换成你想用的 或者删除
# —————————
proxies:
  - {name: 🌐 本机·本地直连, type: direct, udp: true}
  - {name: ⛔️ 禁止·拒绝连接, type: reject}
  - {name: 🌐 DNS_Hijack, type: dns}
proxy_groups: &proxy_groups
    type: select
    proxies:
      - 总模式
      - ALL·延迟最低
      - ALL·负载均衡
      - ALL·故障转移
      - ALL·中国台湾
      - ALL·香港地区
      - ALL·美国地区
      - ALL·日本地区
      - ALL·狮城地区
      - ALL·其它地区
      - ⛔️ 禁止·拒绝连接
      - 🌐 本机·本地直连
    <<: *A
# —————————
proxy-groups:
  - name: 总模式
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/All.svg"
    type: select
    proxies:
      - ALL·延迟最低
      - ALL·负载均衡
      - ALL·故障转移
      - ALL·日本地区
      - ALL·中国台湾
      - ALL·香港地区  
      - ALL·美国地区
      - ALL·狮城地区
      - ALL·其它地区
      - 🌐 本机·本地直连
  - name: 订阅更新
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/Update.svg"
    type: select
    proxies:
      - 🌐 本机·本地直连
      - 总模式
  - name: 小红书
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/XiaoHongShu.svg"
    <<: *proxy_groups
  - name: 抖音
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/DouYin.svg"
    <<: *proxy_groups
  - name: BiliBili
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/BiliBili.svg"
    <<: *proxy_groups
  - name: Steam
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/Steam.svg"
    <<: *proxy_groups
  - name: Apple
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/Apple.svg"
    <<: *proxy_groups
  - name: Microsoft
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/Microsoft.svg"
    <<: *proxy_groups
  - name: Telegram
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/Telegram.svg"
    <<: *proxy_groups
  - name: Discord
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/Discord.svg"
    <<: *proxy_groups
  - name: Spotify
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/Spotify.svg"
    <<: *proxy_groups
  - name: TikTok
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/TikTok.svg"
    <<: *proxy_groups
  - name: YouTube
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/YouTube.svg"
    <<: *proxy_groups
  - name: Netflix
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/Netflix.svg"
    <<: *proxy_groups
  - name: Google
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/Google.svg"
    <<: *proxy_groups
  - name: GoogleFCM
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/GoogleFCM.svg"
    <<: *proxy_groups
  - name: Facebook
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/Facebook.svg"
    <<: *proxy_groups
  - name: OpenAI
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/OpenAI.svg"
    <<: *proxy_groups
  - name: GitHub
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/GitHub.svg"
    <<: *proxy_groups
  - name: Twitter(X)
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/Twitter.svg"
    <<: *proxy_groups
  - name: DNS连接
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/DNS.svg"
    <<: *proxy_groups
  - name: 漏网之鱼
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/HBASE-copy.svg"
    <<: *proxy_groups
  - name: 广告拦截
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/No-ads-all.svg"
    type: select
    proxies:
      - ⛔️ 禁止·拒绝连接
      - 🌐 DNS_Hijack
      - REJECT-DROP
      - PASS
  - name: WebRTC
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/WebRTC.svg"
    type: select
    proxies:
      - ⛔️ 禁止·拒绝连接
      - 🌐 DNS_Hijack
      - REJECT-DROP
      - PASS
  - name: ALL·延迟最低
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/Return.svg"
    type: url-test
    <<: *A
  - name: ALL·负载均衡
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/Return.svg"
    type: load-balance
    strategy: round-robin
    <<: *A
  - name: ALL·故障转移
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/Return.svg"
    type: fallback
    <<: *A
  - name: ALL·日本地区
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/JP.svg"
    filter: "^(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)).*$"
    <<: *All
  - name: ALL·中国台湾
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/CN.svg"
    filter: "^(?=.*(台|新北|彰化|TW|Taiwan|taipei)).*$"
    <<: *All
  - name: ALL·香港地区
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/HK.svg"
    filter: "^(?=.*(港|HK|hk|Hong Kong|HongKong|hongkong)).*$"
    <<: *All
  - name: ALL·美国地区
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/US.svg"
    filter: "^(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)).*$"
    <<: *All
  - name: ALL·狮城地区
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/Singapore.svg"
    filter: "^(?=.*(新加坡|坡|狮城|SG|Singapore)).*$"
    <<: *All
  - name: ALL·其它地区
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/Globe.svg"
    filter: "^(?!.*(港|HK|hk|Hong Kong|HongKong|hongkong|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|台|新北|彰化|TW|Taiwan|新加坡|坡|狮城|SG|Singapore|灾|网易|Netease|套餐|重置|剩余|到期|订阅|群|账户|流量|有效期|时间|官网|拒绝|DNS|Ch|网址|售|防失)).*$"
    <<: *All
  - name: 特殊地址
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/app/icon/User.svg"
    type: select
    url: https://www.baidu.com/favicon.ico
    interval: *Time
    proxies:
      - 🌐 本机·本地直连
      - ⛔️ 禁止·拒绝连接
# —————————
rule-anchor:
  Local: &Local
    {type: file, behavior: classical, format: text}
  Classical: &Classical
    {type: http, behavior: classical, format: text, interval: *Time}
  IPCIDR: &IPCIDR
    {type: http, behavior: ipcidr, format: mrs, interval: *Time}
  Domain: &Domain
    {type: http, behavior: domain, format: mrs, interval: *Time}
# —————————
# Github Actions 每日自动同步跟随更新
# 规则提供者: https://github.com/MetaCubeX/meta-rules-dat
rule-providers:
  自定义规则: # 主要用于广告/业务误杀自定义放行
    <<: *Local
    path: ./etc/自定义规则.list
  WebRTC_端/域:
    <<: *Classical
    path: ./rules/WebRTC.list
    url: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@main/box_bll/clash/rules/WebRTC.list"
  CN_IP:
    <<: *IPCIDR
    path: ./rules/CN_IP.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo-lite/geoip/cn.mrs"
  CN_域:
    <<: *Domain
    path: ./rules/CN_域.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/cn.mrs"
  No-ads-all_域:
    <<: *Domain
    path: ./rules/No-ads-all.mrs
    url: "https://anti-ad.net/mihomo.mrs"
  XiaoHongShu_域:
    <<: *Domain
    path: ./rules/XiaoHongShu.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/xiaohongshu.mrs"
  DouYin_域:
    <<: *Domain
    path: ./rules/DouYin.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/douyin.mrs"
  BiliBili_域:
    <<: *Domain
    path: ./rules/BiliBili.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/bilibili.mrs"
  BiliBili_IP:
    <<: *IPCIDR
    path: ./rules/BiliBili_IP.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo-lite/geoip/bilibili.mrs"
  Steam_域:
    <<: *Domain
    path: ./rules/Steam.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/steam.mrs"
  TikTok_域:
    <<: *Domain
    path: ./rules/TikTok.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/tiktok.mrs"
  Spotify_域:
    <<: *Domain
    path: ./rules/Spotify.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/spotify.mrs"
  Facebook_域:
    <<: *Domain
    path: ./rules/Facebook.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/facebook.mrs"
  Facebook_IP:
    <<: *IPCIDR
    path: ./rules/Facebook_IP.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo-lite/geoip/facebook.mrs"
  Telegram_域:
    <<: *Domain
    path: ./rules/Telegram.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/telegram.mrs"
  Telegram_IP:
    <<: *IPCIDR
    path: ./rules/Telegram_IP.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo-lite/geoip/telegram.mrs"
  YouTube_域:
    <<: *Domain
    path: ./rules/YouTube.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/youtube.mrs"
  Google_域:
    <<: *Domain
    path: ./rules/Google.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/google.mrs"
  Google_IP:
    <<: *IPCIDR
    path: ./rules/Google_IP.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo-lite/geoip/google.mrs"
  GoogleFCM_域:
    <<: *Domain
    path: ./rules/GoogleFCM.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/googlefcm.mrs"
  Microsoft_域:
    <<: *Domain
    path: ./rules/Microsoft.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/microsoft.mrs"
  Apple_域:
    <<: *Domain
    path: ./rules/Apple.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/apple.mrs"
  Apple_IP:
    <<: *IPCIDR
    path: ./rules/Apple_IP.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo-lite/geoip/apple.mrs"
  OpenAI_域:
    <<: *Domain
    path: ./rules/OpenAI.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/openai.mrs"
  Netflix_域:
    <<: *Domain
    path: ./rules/Netflix.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/netflix.mrs"
  Netflix_IP:
    <<: *IPCIDR
    path: ./rules/Netflix_IP.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo-lite/geoip/netflix.mrs"
  Discord_域:
    <<: *Domain
    path: ./rules/Discord.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/discord.mrs"
  GitHub_域:
    <<: *Domain
    path: ./rules/GitHub.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/github.mrs"
  Twitter_域:
    <<: *Domain
    path: ./rules/Twitter.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/twitter.mrs"
  Twitter_IP:
    <<: *IPCIDR
    path: ./rules/Twitter_IP.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo-lite/geoip/twitter.mrs"
  Private_域:
    <<: *Domain
    path: ./rules/Private.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/private.mrs"
  Private_IP:
    <<: *IPCIDR
    path: ./rules/Private_IP.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo-lite/geoip/private.mrs"
# —————————
rules:
  - DST-PORT,53,🌐 DNS_Hijack
  - DST-PORT,853,DNS连接
  - RULE-SET,自定义规则,特殊地址
  - RULE-SET,WebRTC_端/域,WebRTC
  - RULE-SET,No-ads-all_域,广告拦截
  - PROCESS-NAME,com.ss.android.ugc.aweme,抖音
  - RULE-SET,DouYin_域,抖音
  - PROCESS-NAME,com.xingin.xhs,小红书
  - RULE-SET,XiaoHongShu_域,小红书
  - PROCESS-NAME,tv.danmaku.bili,BiliBili
  - RULE-SET,BiliBili_域,BiliBili
  - RULE-SET,BiliBili_IP,BiliBili,no-resolve
  - RULE-SET,Steam_域,Steam
  - RULE-SET,GitHub_域,GitHub
  - RULE-SET,Discord_域,Discord
  - RULE-SET,TikTok_域,TikTok
  - RULE-SET,Twitter_域,Twitter(X)
  - RULE-SET,Twitter_IP,Twitter(X),no-resolve
  - RULE-SET,YouTube_域,YouTube
  - RULE-SET,GoogleFCM_域,GoogleFCM
  - RULE-SET,Google_域,Google
  - RULE-SET,Google_IP,Google,no-resolve
  - RULE-SET,Netflix_域,Netflix
  - RULE-SET,Netflix_IP,Netflix,no-resolve
  - RULE-SET,Spotify_域,Spotify
  - RULE-SET,Facebook_域,Facebook
  - RULE-SET,Facebook_IP,Facebook,no-resolve
  - RULE-SET,OpenAI_域,OpenAI
  - RULE-SET,Apple_域,Apple
  - RULE-SET,Apple_IP,Apple,no-resolve
  - RULE-SET,Microsoft_域,Microsoft
  - RULE-SET,Telegram_域,Telegram
  - RULE-SET,Telegram_IP,Telegram,no-resolve
  - RULE-SET,Private_域,🌐 本机·本地直连
  - RULE-SET,Private_IP,🌐 本机·本地直连,no-resolve
  - RULE-SET,CN_域,🌐 本机·本地直连
  - RULE-SET,CN_IP,🌐 本机·本地直连
  - MATCH,漏网之鱼
# —————————
