name: Update File

on:
  schedule:
    - cron: '30 22 * * *' # UTC 22:30 = 北京时间次日6:30
  workflow_dispatch: # 允许手动触发

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: 检查存储库
        uses: actions/checkout@v4

      - name: 下载新配置
        run: |
          curl -s -o "mihomoWiki_rule-set_config.yaml" \
            "https://wiki.metacubex.one/example/mrs"
          curl -s -o "mihomoWiki_geox_config.yaml" \
            "https://wiki.metacubex.one/example/geox"

          curl -s -o "yiteei_redir-host_config.yaml" \
            "https://raw.githubusercontent.com/yiteei/Share/refs/heads/Proxy/config/redir-host.yaml"
          curl -s -o "yiteei_fake-ip_config.yaml" \
            "https://raw.githubusercontent.com/yiteei/Share/refs/heads/Proxy/config/fake-ip.yaml"

          curl -s -o "JohnsonRan_AIB.yaml" \
            "https://raw.githubusercontent.com/JohnsonRan/CRules/refs/heads/master/config/AIB.yaml"
          curl -s -o "JohnsonRan_AIO.yaml" \
            "https://raw.githubusercontent.com/JohnsonRan/CRules/refs/heads/master/config/AIO.yaml"

          curl -s -o "Surfing_config.yaml" \
            "https://raw.githubusercontent.com/GitMetaio/Surfing/refs/heads/main/box_bll/clash/config.yaml"
          curl -s -o "akashaproxy_config.yaml" \
            "https://raw.githubusercontent.com/akashaProxy/akashaProxy/refs/heads/master/module/clash/config.yaml.example"
          curl -s -o "ClashMix_config.yaml" \
            "https://raw.githubusercontent.com/AXEVO/Clash-MIX/refs/heads/Clash-MIX-4.0/Clash/Clash%E9%85%8D%E7%BD%AE.yaml"
          curl -s -o "boxProxy_config.yaml" \
            "https://raw.githubusercontent.com/boxproxy/box/refs/heads/master/box/mihomo/config.yaml"

          curl -s -o "iKelee_Clash_Sample_Config.yaml" \
            "https://raw.githubusercontent.com/luestr/ProxyResource/refs/heads/main/Tool/Clash/Config/Clash_Sample_Configuration_By_iKeLee.yaml"

          curl -s -o "666OS_OneSmart_Config.yaml" \
            "https://raw.githubusercontent.com/666OS/YYDS/main/mihomo/config/OneSmartPro.yaml"
          curl -s -o "666OS_OneSmart_Lite_Config.yaml" \
            "https://raw.githubusercontent.com/666OS/YYDS/main/mihomo/config/OneSmart.yaml"
          curl -s -o "HenryChiao_MihomoAIO_SmartProPlus_Config.yaml" \
            "https://raw.githubusercontent.com/HenryChiao/MIHOMO_AIO/refs/heads/main/CONFIG/mihomopro.yaml"

          curl -s -o "666OS_MihomoPro_Config.yaml" \
            "https://raw.githubusercontent.com/666OS/YYDS/main/mihomo/config/MihomoPro.yaml"
          curl -s -o "666OS_Mihomo_OneTouch_Config.yaml" \
            "https://raw.githubusercontent.com/666OS/YYDS/main/mihomo/config/OneTouch.yaml"

      - name: 提交并推送更改
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update files" || echo "No changes to commit"
          git push
